"use client";

import { motion, AnimatePresence } from "framer-motion";
import { Tabs, TabsContent, TabsList } from "@/components/ui/tabs";
import { UrlInput } from "@/components/url-input";
import { FileTree } from "@/components/file-tree";
import { ScoreCard } from "@/components/score-card";
import { AIInsights } from "@/components/ai-insights";
import { ArchitectureDiagram } from "@/components/architecture-diagram";
import { DataFlowDiagram } from "@/components/data-flow-diagram";
import { CoreFeaturesPanel } from "@/components/core-features-panel";
import { KeyConceptsPanel } from "@/components/key-concepts-panel";
import { DependencyGraph } from "@/components/dependency-graph";
import { RefactorsPanel } from "@/components/refactors-panel";
import { AutomationsPanel } from "@/components/automations-panel";
import { IssuesPanel, SuggestedIssue } from "@/components/issues-panel";
import { AnalysisHeader } from "@/components/analysis-header";
import { LoadingSkeleton } from "@/components/loading-skeleton";
import { RecentAnalyses } from "@/components/recent-analyses";
import { FeatureGate } from "@/components/feature-gate";
import { useAnalysis } from "@/hooks/use-analysis";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { ScrollArea, ScrollBar } from "@/components/ui/scroll-area";
import { Badge } from "@/components/ui/badge";
import { cn } from "@/lib/utils";
import { HugeiconsIcon } from "@hugeicons/react";
import {
  AlertCircleIcon,
  Rotate01Icon,
  GitBranchIcon,
  WorkflowSquare10Icon,
  Wrench01Icon,
  ZapIcon,
  Refresh01Icon,
  Database01Icon,
  Bug01Icon,
  GitPullRequestIcon,
} from "@hugeicons/core-free-icons";
import { useMemo } from "react";

import { fadeIn, slideUp } from "./animations";
import { SectionHeader } from "./section-header";
import { TabTriggerItem } from "./tab-trigger-item";
import { EmptyState } from "./empty-state";
import Testimonials from "../testimonial/testimonial";
// import { PRSuggestionsPanel } from "../pr-suggestions-panel";

export function RepoAnalyzer() {
  const {
    analyze,
    analyzeBranch,
    status,
    result,
    tier,
    reset,
    refresh,
    isLoading,
    isComplete,
    hasError,
    isIdle,
    isCached,
    currentBranch,
  } = useAnalysis();

  const handleReset = () => {
    reset();
    window.scrollTo({
      top: 0,
      behavior: "smooth",
    });
  };

  // Generate suggested issues from analysis results
  const suggestedIssues = useMemo((): SuggestedIssue[] => {
    if (!result) return [];

    const issues: SuggestedIssue[] = [];

    // Convert insights to issues
    result.insights?.forEach((insight, index) => {
      if (insight.type === "weakness" || insight.type === "warning") {
        const issueType: SuggestedIssue["type"] =
          insight.type === "warning" ? "bug" : "improvement";
        const priority: SuggestedIssue["priority"] =
          insight.priority === "critical"
            ? "critical"
            : insight.priority === "high"
              ? "high"
              : insight.priority === "medium"
                ? "medium"
                : "low";

        issues.push({
          id: `insight-${index}`,
          type: issueType,
          title: insight.title,
          description: insight.description,
          body: `## ${insight.title}

### Category
${insight.category}

### Description
${insight.description}

### Priority
${insight.priority}

${
  insight.affectedFiles?.length
    ? `### Affected Files
${insight.affectedFiles.map((f) => `- \`${f}\``).join("\n")}`
    : ""
}

---
*Generated by Repolyze analysis*`,
          labels: [
            insight.type === "warning" ? "bug" : "enhancement",
            insight.category?.toLowerCase().replace(/\s+/g, "-") || "general",
            `priority-${insight.priority}`,
          ].filter(Boolean),
          priority,
          source: "insight",
          affectedFiles: insight.affectedFiles,
        });
      }
    });

    // Convert high-priority automations to issues
    result.automations?.forEach((automation, index) => {
      if (automation.priority === "high" && automation.type === "issue") {
        issues.push({
          id: `automation-${index}`,
          type: "improvement",
          title: automation.title,
          description: automation.description,
          body: automation.body,
          labels: automation.labels || ["enhancement"],
          priority: "high",
          source: "automation",
          estimatedEffort: (automation as { estimatedEffort?: string })
            .estimatedEffort,
          affectedFiles: (automation as { files?: string[] }).files,
        });
      }
    });

    return issues;
  }, [result]);

  return (
    <div className="w-full">
      <div className="space-y-6 sm:space-y-8 lg:space-y-10">
        <section className="w-full">
          <UrlInput onAnalyze={analyze} isLoading={isLoading} />
        </section>

        <AnimatePresence mode="wait">
          {hasError && (
            <motion.section
              key="error"
              variants={slideUp}
              initial="hidden"
              animate="visible"
              exit="hidden"
              transition={{ duration: 0.3 }}
              className="w-full"
            >
              <Card className="border-destructive/30 bg-destructive/5">
                <CardContent className="p-8 sm:p-10 lg:p-12">
                  <div className="flex flex-col items-center text-center max-w-md mx-auto">
                    <div className="w-14 h-14 rounded-full bg-destructive/10 flex items-center justify-center mb-5">
                      <HugeiconsIcon
                        icon={AlertCircleIcon}
                        className="w-7 h-7 text-destructive"
                      />
                    </div>
                    <h3 className="text-lg font-semibold text-foreground mb-2">
                      Analysis Failed
                    </h3>
                    <p className="text-sm text-muted-foreground mb-6 leading-relaxed">
                      {status.error ||
                        "Something went wrong while analyzing the repository."}
                    </p>
                    <Button
                      onClick={handleReset}
                      variant="outline"
                      className="border-border hover:bg-muted"
                    >
                      <HugeiconsIcon
                        icon={Rotate01Icon}
                        className="w-4 h-4 mr-2"
                      />
                      Try Again
                    </Button>
                  </div>
                </CardContent>
              </Card>
            </motion.section>
          )}

          {isLoading && (
            <motion.section
              key="loading"
              variants={fadeIn}
              initial="hidden"
              animate="visible"
              exit="hidden"
              transition={{ duration: 0.2 }}
              className="w-full"
            >
              <LoadingSkeleton status={status} />
            </motion.section>
          )}

          {isComplete && result?.metadata && (
            <motion.div
              key="results"
              variants={fadeIn}
              initial="hidden"
              animate="visible"
              transition={{ duration: 0.3 }}
              className="space-y-6 sm:space-y-8 lg:space-y-10"
            >
              {/* Cache indicator with branch info */}
              {isCached && (
                <motion.div
                  initial={{ opacity: 0, y: -10 }}
                  animate={{ opacity: 1, y: 0 }}
                  className="flex items-center justify-center gap-3 flex-wrap"
                >
                  <Badge
                    variant="secondary"
                    className="gap-1.5 px-3 py-1 bg-primary/10 text-primary border-primary/20"
                  >
                    <HugeiconsIcon
                      icon={Database01Icon}
                      className="w-3.5 h-3.5"
                    />
                    Loaded from cache
                  </Badge>
                  {result.branch && (
                    <Badge variant="outline" className="gap-1.5 px-3 py-1">
                      <HugeiconsIcon
                        icon={GitBranchIcon}
                        className="w-3.5 h-3.5"
                      />
                      {result.branch}
                    </Badge>
                  )}
                  <Button
                    variant="ghost"
                    size="sm"
                    onClick={refresh}
                    disabled={isLoading}
                    className="h-7 gap-1.5 text-xs hover:bg-primary/10 hover:text-primary"
                  >
                    <HugeiconsIcon
                      icon={Refresh01Icon}
                      className="w-3.5 h-3.5"
                    />
                    Refresh Analysis
                  </Button>
                </motion.div>
              )}

              <motion.section
                initial={{ opacity: 0, y: 12 }}
                animate={{ opacity: 1, y: 0 }}
                transition={{ duration: 0.3, delay: 0.05 }}
                className="w-full"
              >
                <AnalysisHeader
                  metadata={result.metadata}
                  techStack={result.techStack}
                  summary={result.summary}
                  result={result}
                  branch={result.branch || currentBranch}
                  availableBranches={result.availableBranches}
                  onBranchChange={analyzeBranch}
                  isLoading={isLoading}
                  tier={tier}
                />
              </motion.section>

              {/* Score Card + AI Insights */}
              <motion.section
                initial={{ opacity: 0, y: 12 }}
                animate={{ opacity: 1, y: 0 }}
                transition={{ duration: 0.3, delay: 0.15 }}
                className="w-full"
              >
                <SectionHeader title="Analysis Overview" />
                <div className="mt-4 grid grid-cols-1 md:grid-cols-2 gap-4 sm:gap-6">
                  {result.scores && <ScoreCard scores={result.scores} />}
                  <FeatureGate
                    tier={tier}
                    feature="aiInsights"
                    featureLabel="AI-powered code insights and recommendations"
                  >
                    {result.insights && result.insights.length > 0 && (
                      <AIInsights insights={result.insights} />
                    )}
                  </FeatureGate>
                </div>
              </motion.section>

              {/* Core Features & Key Concepts */}
              {((result.coreFeatures && result.coreFeatures.length > 0) ||
                (result.keyConcepts && result.keyConcepts.length > 0)) && (
                <motion.section
                  initial={{ opacity: 0, y: 12 }}
                  animate={{ opacity: 1, y: 0 }}
                  transition={{ duration: 0.3, delay: 0.18 }}
                  className="w-full"
                >
                  <SectionHeader title="Deep Dive" />
                  <div className="mt-4 grid grid-cols-1 md:grid-cols-2 gap-4 sm:gap-6">
                    {result.coreFeatures && result.coreFeatures.length > 0 && (
                      <CoreFeaturesPanel features={result.coreFeatures} />
                    )}
                    {result.keyConcepts && result.keyConcepts.length > 0 && (
                      <KeyConceptsPanel concepts={result.keyConcepts} />
                    )}
                  </div>
                </motion.section>
              )}

              {/* Data Flow Diagram */}
              <motion.section
                initial={{ opacity: 0, y: 12 }}
                animate={{ opacity: 1, y: 0 }}
                transition={{ duration: 0.3, delay: 0.25 }}
                className="w-full"
              >
                <SectionHeader title="Data Flow" icon={WorkflowSquare10Icon} />
                <div className="mt-4">
                  <FeatureGate
                    tier={tier}
                    feature="dataFlow"
                    featureLabel="Visual data flow diagram between components"
                  >
                    {result.dataFlow?.nodes &&
                    result.dataFlow.nodes.length > 0 ? (
                      <DataFlowDiagram
                        nodes={result.dataFlow.nodes}
                        edges={result.dataFlow.edges || []}
                      />
                    ) : (
                      <EmptyState
                        icon={WorkflowSquare10Icon}
                        title="No Data Flow Information"
                        description="Data flow visualization is not available for this repository."
                      />
                    )}
                  </FeatureGate>
                </div>
              </motion.section>

              {/* File Tree */}
              {result.fileTree && result.fileStats && (
                <motion.section
                  initial={{ opacity: 0, y: 12 }}
                  animate={{ opacity: 1, y: 0 }}
                  transition={{ duration: 0.3, delay: 0.1 }}
                  className="w-full"
                >
                  <SectionHeader title="Repository Structure" />
                  <div className="mt-4">
                    <FileTree
                      tree={result.fileTree}
                      stats={result.fileStats}
                      branch={result.branch || currentBranch}
                    />
                  </div>
                </motion.section>
              )}

              {/* Architecture Diagram */}
              <motion.section
                initial={{ opacity: 0, y: 12 }}
                animate={{ opacity: 1, y: 0 }}
                transition={{ duration: 0.3, delay: 0.2 }}
                className="w-full"
              >
                <SectionHeader title="Architecture" icon={GitBranchIcon} />
                <div className="mt-4">
                  {result.architecture && result.architecture.length > 0 ? (
                    <ArchitectureDiagram components={result.architecture} />
                  ) : (
                    <EmptyState
                      icon={GitBranchIcon}
                      title="No Architecture Data"
                      description="Architecture visualization is not available for this repository."
                    />
                  )}
                </div>
              </motion.section>

              {/* Dependency Graph */}
              {result.dependencyGraph?.nodes &&
                result.dependencyGraph.nodes.length > 0 && (
                  <motion.section
                    initial={{ opacity: 0, y: 12 }}
                    animate={{ opacity: 1, y: 0 }}
                    transition={{ duration: 0.3, delay: 0.22 }}
                    className="w-full"
                  >
                    <SectionHeader
                      title="Dependency Map"
                      icon={WorkflowSquare10Icon}
                    />
                    <div className="mt-4">
                      <FeatureGate
                        tier={tier}
                        feature="dataFlow"
                        featureLabel="Interactive dependency graph between components"
                      >
                        <DependencyGraph
                          nodes={result.dependencyGraph.nodes}
                          edges={result.dependencyGraph.edges || []}
                        />
                      </FeatureGate>
                    </div>
                  </motion.section>
                )}

              {/* Refactors, Automations & Issues Tabs */}
              <motion.section
                initial={{ opacity: 0, y: 12 }}
                animate={{ opacity: 1, y: 0 }}
                transition={{ duration: 0.3, delay: 0.3 }}
                className="w-full"
              >
                <SectionHeader title="Recommendations & Actions" />

                <div className="mt-4">
                  <Tabs defaultValue="issues" className="w-full">
                    <ScrollArea className="w-full pb-1">
                      <TabsList
                        className={cn("inline-flex h-10 sm:h-11 p-1 gap-1")}
                      >
                        <TabTriggerItem
                          value="issues"
                          icon={Bug01Icon}
                          label="Issues"
                          count={suggestedIssues.length}
                        />
                        <TabTriggerItem
                          value="automations"
                          icon={ZapIcon}
                          label="Automations"
                          count={result.automations?.length}
                        />
                        <TabTriggerItem
                          value="refactors"
                          icon={Wrench01Icon}
                          label="Refactors"
                          count={
                            result.refactors?.filter(
                              (r) =>
                                r.title &&
                                r.description &&
                                r.impact &&
                                r.effort,
                            ).length
                          }
                        />

                        {/* <TabTriggerItem
                          value="pull-requests"
                          icon={GitPullRequestIcon}
                          label="PRs"
                          count={result.pullRequests?.length}
                        /> */}
                      </TabsList>
                      <ScrollBar
                        orientation="horizontal"
                        className="invisible"
                      />
                    </ScrollArea>

                    <TabsContent
                      value="refactors"
                      className="mt-4 sm:mt-6 focus-visible:outline-none"
                    >
                      <motion.div
                        initial={{ opacity: 0 }}
                        animate={{ opacity: 1 }}
                        transition={{ duration: 0.2 }}
                      >
                        <RefactorsPanel
                          refactors={result.refactors || []}
                          repoFullName={result.metadata?.fullName}
                        />
                      </motion.div>
                    </TabsContent>

                    <TabsContent
                      value="automations"
                      className="mt-4 sm:mt-6 focus-visible:outline-none"
                    >
                      <motion.div
                        initial={{ opacity: 0 }}
                        animate={{ opacity: 1 }}
                        transition={{ duration: 0.2 }}
                      >
                        {result.automations && result.automations.length > 0 ? (
                          <AutomationsPanel
                            automations={result.automations}
                            repoFullName={result.metadata?.fullName}
                          />
                        ) : (
                          <EmptyState
                            icon={ZapIcon}
                            title="No Automation Suggestions"
                            description="No automation opportunities were identified."
                          />
                        )}
                      </motion.div>
                    </TabsContent>

                    <TabsContent
                      value="issues"
                      className="mt-4 sm:mt-6 focus-visible:outline-none"
                    >
                      <motion.div
                        initial={{ opacity: 0 }}
                        animate={{ opacity: 1 }}
                        transition={{ duration: 0.2 }}
                      >
                        <FeatureGate
                          tier={tier}
                          feature="issues"
                          featureLabel="Auto-generated GitHub issues from analysis"
                        >
                          <IssuesPanel
                            repoFullName={result.metadata?.fullName || ""}
                            suggestedIssues={suggestedIssues}
                          />
                        </FeatureGate>
                      </motion.div>
                    </TabsContent>
                    {/* <TabsContent
                      value="pull-requests"
                      className="mt-4 sm:mt-6 focus-visible:outline-none"
                    >
                      <motion.div
                        initial={{ opacity: 0 }}
                        animate={{ opacity: 1 }}
                        transition={{ duration: 0.2 }}
                      >
                        {result.pullRequests &&
                        result.pullRequests.length > 0 ? (
                          <PRSuggestionsPanel
                            suggestions={result.pullRequests}
                            repoFullName={result.metadata?.fullName || ""}
                          />
                        ) : (
                          <EmptyState
                            icon={GitPullRequestIcon}
                            title="No PR Suggestions"
                            description="No pull request opportunities were identified."
                          />
                        )}
                      </motion.div>
                    </TabsContent> */}
                  </Tabs>
                </div>
              </motion.section>

              {/* Reset Button */}
              <motion.section
                initial={{ opacity: 0 }}
                animate={{ opacity: 1 }}
                transition={{ duration: 0.3, delay: 0.35 }}
                className="w-full flex justify-center pt-4 pb-8"
              >
                <Button
                  onClick={handleReset}
                  variant="outline"
                  size="lg"
                  className={cn(
                    "group",
                    "border-border hover:border-foreground/20",
                    "hover:bg-muted/50",
                    "transition-all duration-300",
                  )}
                >
                  <HugeiconsIcon
                    icon={Rotate01Icon}
                    className={cn(
                      "w-4 h-4 mr-2 text-muted-foreground",
                      "group-hover:text-foreground",
                      "transition-all duration-500",
                    )}
                  />
                  <span className="text-muted-foreground group-hover:text-foreground transition-colors">
                    Analyze Another Repository
                  </span>
                </Button>
              </motion.section>
            </motion.div>
          )}

          {/* Idle State - Recent Analyses + Testimonials */}
          {isIdle && (
            <motion.div
              key="idle"
              initial={{ opacity: 0 }}
              animate={{ opacity: 1 }}
              exit={{ opacity: 0 }}
              className="space-y-8"
            >
              {/* Recent Analyses */}
              <RecentAnalyses onSelect={analyze} />

              {/* Testimonials */}
              <Testimonials />
            </motion.div>
          )}
        </AnimatePresence>
      </div>
    </div>
  );
}
